(function (window, document) {

	var hottakes = [//'Robot learning researchers just now discovering teleoperation is the most baffling trend of 2023.',
		//"Roboticists drastically underestimate how refined a technology needs to be before it's adopted.",
		//"Don't say I'm mid career. This career is based. On god fr.",
		//'"Centers" proliferate like rabbits at University of Illinois.',
		"Large amounts of data enables a robot to do a task? More sensing modalities are helpful? Your paper is a snoozer, do better.",
		"Few-shot learning and meta-learning are frustratingly hard to get working, but the future of AI & robotics demands that we tackle these problems head-on.",
		"People value expertise only after being hurt by their own stupidity.",
		"“Getting it to work” isn't the goal of research — it's the start.",
		"Robotics produces fewer talented PhDs than the number of top faculty positions, so the average quality of junior faculty has declined over recent years.",
		"We\'ll need to endure a few years of shoddy “LLM+robotics” papers before we realize the true value of LLMs to the field.",
		'<b>if</b> CV.contains("fuzzy") <b>then</b> delete(email) <b>end</b>.',
		"Hardware is hard.  It's right there in the name.",
		"A proposal's primary function is not to propose sound ideas, it's to propose sound activities.",
		"One faction in robotics is excited about robots that clumsily do many things, while another is excited about robots that do one thing well. They don't really get each other.",
		"Any serious robotics project will spend $10 on software engineering for every $1 spent on hardware. At least.",
		"Robot hardware has gotten so cheap but the expertise to make robots work has not caught up.  Universities now have a bunch of expensive statues.",
		"Me, every time I fire up a new ROS project: 10 reinstalls, 5 upgrades, 6 downgrades, and with 20 open Google tabs later... “Oh yeah, that's why I hate using ROS.”",
		"Humanity is currently facing a COVID-caused cognitive decline through all levels of society",
		"The success of a meritocracy rests on how well it occupies the non-meritorious majority",
		"Fundamentally, robot learning argues that gathering data is easier than installing software.  That's a pretty solid argument, TBH.",
		"If a sampling-based motion planning paper shows results only in 2d environments, you'd better roll your eyes. Grid search will always be better in 2D.",
		"Because of grade inflation, a 4.0 GPA means nothing nowadays",
		"A professor's control authority over a student is quite low, but a parent's control authority over a teenager is essentially negative.",
		"The 80/20 rule of robotics: about 80% of all robots in a research lab are entirely inoperable, and of the 20% that are operable, 80% of those are idle.",
		"Expecting current-gen AI to solve manipulation is like expecting your dog to do dishes.",
		"The hot trend is to use AI for robots to do a lot of things... badly. I will have no confidence in this approach until AI can get one thing done well.",
		"The question shouldn't be “can learning solve it?” It should be “is learning <i>the most efficient way</i> to solve it?”",
		"If you want to build real-world robots, study theory first. Otherwise you won't know what's solved, how to name things, and how to establish meaningful APIs.",
		"A simple poorly-performing method from a well-known group will be far better cited than a good complex method, because it will be the baseline that everyone beats.",
		"If robotics can't keep learning research honest, what hope is there for the rest of AI?",
		"Learning Cartesian control doesn't make a method “any-robot”, “universal”, or “zero-shot generalization between robots”.  It's “using the most standard feature of robot arms”.",
		"“Back in the day, we used to aspire to solve classes of problems, but now too many papers aspire only to solve problem instances” - Dmitry Berenson (paraphrased)",
		"Tech optimism helps the rich get richer.",
		"High-tech companies getting into robotics don't understand that moving mass is fundamentally unlike moving bits.",
		"If physics, astronomy, and supercomputing can get their researchers to work together, why can't robotics?",
		"Forcing robotics researchers to stop reinventing the wheel and work together would be a more efficient use of taxpayer $$ than current funding models.",
		"The American higher education system is existentially vulnerable to cultural shift in China and India.",
		"A well-written research plan should never fail due to the result of a scientific unknown. Never claim that you'll force the value of an unknown, e.g., “method X will achieve a Y% success rate”.",
		"The level of student interest in tackling hard, deep problems has cratered.  That's the most insidious problem facing AI-adjacent fields today.",
		"“People don't get smarter, they just grow up.” - David Forsyth",
		"Real robot experiments are useless unless you're either testing the correctness of your assumptions, or learning about the world itself.",
		"Go ahead and overfit to a task. Generalization between environments is more important.",
		"“Real-world” means an entirely different thing to people in the real world.",
		"Comprehension of reality is optional today.",
		"Understanding is not just accurate prediction, it's also explainability.",
		"A field is successful when a fresh student can build a profitable business in 2 years with a $5m investment.",
		"Training students to embrace hype will be academia's downfall.",
		"When robotics and learning papers say “X enables Y” they're using the loosest possible definition of “enable.”",
		"The number of roboticists trying to answer deep, fundamental questions about the nature of autonomy is shrinking at a rapid rate — outpaced only by the number of students paying attention to them.",
		"A researcher reaches maturity when they stop asking “what can I do” and begin to ponder “what should others do?”",
		'Unlike <a href="https://www.youtube.com/watch?v=WZ_rXp6nYKQ">Murphy Lee</a>, your proposal really does need a hook.',
		"We're so politically polarized because liberalism demands so much of one's character. It would get less backlash if a little racism, xenophobia, and sexism were tolerated. Just a tad. Like a free pass for 3 slurs and 10 microagressions per year.",
		"At what point did academia decide that helping students is part of our job?",
		"Competition between scientists is a waste of talent and taxpayer dollars.",
		"NSF's model is that professors should be scholar-philanthropists.",
		"“I think it needs more data” is never an insightful explanation.",
		"Home improvement is a humbling experience that teaches you not to underestimate the difficulty of robotics.",
		"Those scoundrels, Google Docs and Overleaf, have robbed me of the professorial thrill of writing unintelligible notes scribbled in red ink and squeezed into tiny margins.",
		"A grad student works on 2-3 tasks per week; a postdoc 6-10; and an assistant professor 20-40. Post-tenure is spent battling either exponential growth or decay in this number.",
		"Don't forget that rhetoric, logic, reference, analysis, and anecdotal observations can make perfectly convincing arguments. Experiments aren't the only way.",
		"Cloud documents are the bane of institutional memory. It's too easy to forget what exists, where to find it, and who has access. Paper has the advantage of physicality; it demands headspace and doesn't evaporate when someone quits.",
		"UIUC: a great school, in an ok city, in a good state.",
		"The modern professor succeeds by generating activity rather than insight.",
		"Patents are less protective for a robotics company than data, infrastructure, and know-how.",
		"Learning makes for a great tool but a poor North Star for research.",
		"“Move fast and break things” might work well for Facebook; much less so for robotcs",
		"I should just drag out a 10 year old paper and rewrite it for modern audiences as though it's my new invention. It's a tried and true formula!",
		"In old-school research the objective was clarity in defining the start and end of the range in which your work applied. Now you get the most applause for a few starting examples that inspire others to believe there is no end.",
		"We all know that reviewing is noisy, but we use this knowledge only to nurse the wounds of rejection, never to downplay our successes.",
		"The hard part of advising is convincing someone not to trust their instincts.",
		"IEPs for cognitive issues in higher education are sheer madness.",
		"The real lesson of deep learning's success has been lost.  As Geoff Hinton will tell you, breakthroughs don't come from chasing hype, but from doggedly committing to unpopular topics.",
		"The key lesson of robotics: physics laughs at your datasets. It farts on your ablation studies. It spits on your scalability.",
		"Assume that everything you read is false until convinced otherwise.  That goes double for academic papers.",
		"You may not know exactly what you want to do, but if you can't do a halfway decent job at pretending, then you're <i>definitely</i> not ready.",
		"So many consequential decisions are made by committees that barely made quorum that day.",
		"Software engineering: the art of keeping your team's bottom performers from screwing things up for the rest.",
		"Middleware is so contentious and fragmented because it takes a couple weeks to throw together a ROS replacement that does 80% of what you want, and you know how it works back to front. But for the next guy, it will do 20% and be nearly impossible to use.",
		"As you get older, not only do your farts cease to stink, but they become a familiar, comforting aroma.",
		"Want to distinguish yourself in a crowded tech field?  Show that you have real grit.  Grit's a valuable resource nowadays.",
		"More and more, I find myself sounding defensive when I try to talk about the positives of AI.",
		"Every humanoid robot researcher is deeply skeptical about humanoid robot startups. This alone should tell you that the current wave of interest is doomed to fail.",
		"A research plan must involve minimal amounts of hope.",
		"The most damning problem with robotics research is that it rarely builds on the past.",
		"With the recent rightward swing of the political pendulum, I hope academia can refocus on academics rather than trying to be everything to everyone. ",
		"Humanity's cognitive implosion before AI conquered the world was such a twist ending!",
		"We'd make just as much scientific progress if we fired 90% of professors and gave the rest time and space to just be weird.",
		"People get addicted to machine learning in the same way as gambling. Soon enough the gambler loses the ability to earn a living any other way.",
		"Students like my hot takes more than they appreciate the ideas in my papers. This cuts me deep.",
		"If you ever despair that your degree is useless or your research has no impact on the world, just remember that some people get their Ph.D.s in education.",
		"It's easy to craft an armor of complexity to defend against a lack of understanding. It's a professor's responsibility to poke holes through that armor to strengthen the person beneath it.",
		"What keeps me up at night is watching the erosion of students' ability and motivation to innovate, and the fear that they are losing the ability to recognize innovation at all.",
		"Whether it's due to COVID, social media, AI hype, or whatever, a shocking fraction of graduate students have their minds have turned to mush.",
		"Higher education is failing to train new cohorts of students with the mentality of engineers, i.e., an intrinsic desire to build things correctly.",
		'The value of "speaking or writing loosely about stuff" and "tinkering with code" is rapidly approaching zero. Align your studies accordingly.',
		"Never mind Dead Internet Theory: Dead Academia Theory isn't far off.",
		"You work a modern UI by pressing buttons until the right thing happens, and then remember that pathway.  Gen Z applies the same model to the physical world rather than seeking understanding of fundamental principles.",
		"Behavior cloning is a band-aid for when you don't know how to implement basic functionality but you need to make a demo.  It's no solution to the autonomy problem.",
		"To succeed in a Ph.D. you need to be either brilliant, industrious, or organized.  Other personality traits, like strong communication, creativity, leadership, or sociability, don't matter. You're a pretender unless you possess one of these essential elements.",
		"Robotics research is becoming hyper-incremental.",
		"Can we all just agree: the acronym of your new method doesn't belong in the title.",
		"AI just shifts the hard problem in software engineering from generating code to reading code.",
		"Once AI makes content generation sufficiently cheap, content discrimination will be the only thing with value.",
		"Humans will be used as actuators for AI bosses far sooner than robots replace human labor.",
		"The information economy will have no use for B and C students by the end of the 2020's.  Get outside and learn a trade, kids.",
		"LLMs can provide robots with common-sense reasoning -- the same kind of reasoning that takes a programmer 10 minutes to implement.",
		"Education value for the bottom 80% of humanity will crash far sooner than anyone expects.",
		"Middle management will soon be replaced by AI.  The future corporate structure is Owner > AI > Underpaid Monkeys Pushing Atoms Around.",
		'A sure sign that the capitalism game is getting <i>really</i> intense is when oligarchs start referring to basic human needs as "life support."',
		"Humans will serve as actuators for AI bosses far sooner than robots replace human labor.",
		'AI will soon "achieve sentience" not in any profound way, but by optimizing human empathy sufficiently well to convince the average person not to "hurt" it.',
	];

    var content  = document.getElementById('hottake');
	var quote = hottakes[Math.floor(Math.pow(Math.random(),0.5)*hottakes.length)];
	console.log(quote);
	content.innerHTML = quote;

}(this, this.document));
